name: memories-client-ec2-instance
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: SSH Remote Commands
         uses: appleboy/ssh-action@v0.1.5
         with:
          host: ${{secrets.AWS_HOSTNAME}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.AWS_USERNAME }}
          script: |
            cd memories-client-instace-demo
            sudo apt-get update
            sudo apt-get install npm -y
            cd memories-client-instace-demo
            npm install
            npm run build
            pm2 serve build
            sudo mv build /var/www/html/build
            cd /etc/nginx/sites-enabled
            touch new
            chmod +x new
            {
              "Hello": Hello
            } >> new

